### PR TITLE
Remove redundant switch in get_resource

### PR DESCRIPTION
**Pull request by 40Grit**
Probably not valid anymore but I wanted to capture this.

https://github.com/ARMmbed/mbed-client/pull/505

### CODE REVIEW

**Comment by 40Grit** [comment]
@maclobdell

**Comment by loverdeg-ep** [comment]
@teetak01 Any comment on this? Looks like other refactors might be doable in m2mFirmware.cpp as well.

**Comment by teetak01** [comment]
Looks ok, although this code is not used by Device Management client as its old implementation for mbed-client library.

**Comment by loverdeg-ep** [comment]
I had a feeling that was the case.
Any efforts underway to refactor unused stuff out?

**Comment by loverdeg-ep** [comment]
@teetak01 bump^^^

**Comment by teetak01** [comment]
We have nothing active on this area. It is always possible that someone external might be using some of those features, but PDMC does not use those.

**Comment by JanneKiiskila** [comment]
@40Grit  - the release process we have - is a not 100% open source compatible in the way one might want (for various reasons I won't go into). the contribution is OK from my point of view, too. It also removes codelines (which is always a plus). Question is, how do you want this credited - as 40Grit or you true name (or both)? The commit itself will not be visible in our history, as we do a code drop via a few steps to this repository and commit history gets squashed fully.
- So, the mention of the credits will be in changelog (and a new file `CONTRIBUTORS.md`).
- You also have to explicitly answer and agree, that your contribution is OK legally as Apache 2.0 contribution (in and outgoing license for us is the same).

**Comment by loverdeg-ep** [comment]
@JanneKiiskila @teetak01

I don't need the credit, but if this helps to open the gates for community contributions then I'll do whatever it takes.

I'll make the changes from @40Grit and also explicitly type that I agree to the license.

I'd like to hear the various reasons why the release process "is not open source compatible"
Feel free to contact me out of band about it. 
Till then, I'm assuming it's too closely tied to the LWM2M server sources.

This code-base is a work of art; our team would be honored to contribute.

**Comment by 40Grit** [comment]
Any thing more I need to do besides say I agree the code I have contributed through this PR is made under Apache 2.0 license?

I will make the requested changes shortly.

**Comment by JanneKiiskila** [comment]
One more thing, under which identity do you want to be credited for?

**Comment by 40Grit** [comment]
This will require rebase I assume?

@JanneKiiskila 
Also, rereading your comments sounds like i just need to say how i want to be credited and you will handle the rest?

Just put Garrett LoVerde (@40Grit ) in the contributors.md.

**Comment by 40Grit** [comment]
I agree the code I have contributed through this PR is made under Apache 2.0 license.

**Comment by JanneKiiskila** [comment]
Internal PR #1667 filed. It needs to pass our CI Testing + code reviews etc. It was easyily applied with `git format patch` and `git am`, no merge conflicts.

**Comment by 40Grit** [comment]
Status?

**Comment by JanneKiiskila** [comment]
PR should likely go in and come out via Pelion Device Management Client version 3.5.0 release.

**Comment by teetak01** [comment]
Closing. This was part of #53 

thanks for the contribution!

**Pull request closed without merging**
